services:
  postgres:
    container_name: 'gestao_vagas_postgres'
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: gestao_vagas
